// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "UltraSonicAuto.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

UltraSonicAuto::UltraSonicAuto(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void UltraSonicAuto::Initialize()
{
	//initializes the variables to their functions
	speed = Robot::drivetrain->GetPower();
	correction = Robot::drivetrain->GetkP();
	duration = Robot::drivetrain->GetAutoTime();
	delay = Robot::drivetrain->GetDelay();
	position = Robot::drivetrain->GetDirection();

	//SetTimeout(duration + delay);

	//ensures gyro is straight, and sets wrist down to allow use
	Robot::drivetrain->ResetGyro();
	Robot::wrist->DownWristState();
}

// Called repeatedly when this Command is scheduled to run
void UltraSonicAuto::Execute()
{
	Robot::drivetrain->AutoGyroDrive(speed, correction); // user given values to be used in auto to drive forward
}

// Make this return true when this Command no longer needs to run execute()
bool UltraSonicAuto::IsFinished()
{
	return Robot::drivetrain->GetDistance() < 18.000; //stops when ultrasonic reads less than 18 inches
}

// Called once after isFinished returns true
void UltraSonicAuto::End()
{
	Robot::drivetrain->Stop(); // stops when finished
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void UltraSonicAuto::Interrupted()
{
	End(); //safety measure
}
